# Generated by Django 5.2.4 on 2025-09-11 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_ticket_booking_alter_ticket_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='cnic',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='only .com email is accepted (e.g., name@example.com).', regex='^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.com$')]),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='full_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Only Letters are Allowed in name.', regex='^[A-Za-z ]+$')]),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='mobile',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile Number Contain only 11-digits.', regex='^\\d{11}$')]),
        ),
    ]
