# Generated by Django 5.2.4 on 2025-09-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_passenger_cnic_alter_passenger_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi',
            name='taxi_number',
            field=models.CharField(max_length=20),
        ),
    ]
