# Generated by Django 5.2.4 on 2025-09-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_notification_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_active',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_deleted_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
